### ISSUE TITLE
Would love to see conversational web agents

### ISSUE THREAD

**Issue by xhluca** [SkyworkAI/agent-studio#37]
Would love to see conversational web navigation benchmarks like [WebLINX](https://github.com/McGill-NLP/weblinx) and MT-Mind2Web!

**Comment by ltzheng** [comment]
Thanks for bringing this up! Conversational web agents are an exciting field, and WebLINX and MT-Mind2Web are indeed important contributions. We'll add these benchmarks in our paper's next revision.

**Comment by xhluca** [comment]
Looking forward it!
